# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-compiler-plugin"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-compiler-plugin"
      - dependency-name: "io.quarkus:*"
        versions:
          - "[3.28,)"
      - dependency-name: "io.quarkus.platform:quarkus-camel-bom"
        versions:
          - "[3.28,)"
      - dependency-name: "org.apache.activemq:*"
        versions:
          - "[2.43.0,)"
    target-branch: "3.9.x"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-compiler-plugin"
      - dependency-name: "io.quarkus:*"
        versions:
          - "[3.21,)"
      - dependency-name: "io.quarkus.platform:quarkus-camel-bom"
        versions:
          - "[3.21,)"
      - dependency-name: "org.apache.activemq:*"
        versions:
          - "[2.41.0,)"
    target-branch: "3.7.x"
