# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-compiler-plugin"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-compiler-plugin"
      - dependency-name: "io.quarkus:quarkus-bom"
        versions: "[3.9,)"
      - dependency-name: "io.quarkus.platform:quarkus-camel-bom"
        versions: "[3.9,)"
      - dependency-name: "org.apache.activemq:*"
        versions: "[2.33.0,)"
    target-branch: "3.2.x"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-compiler-plugin"
      - dependency-name: "io.quarkus:quarkus-bom"
        versions: "[3.8,)"
      - dependency-name: "io.quarkus.platform:quarkus-camel-bom"
        versions: "[3.8,)"
    target-branch: "3.1.x"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-compiler-plugin"
      - dependency-name: "io.quarkus:quarkus-bom"
        versions: "[3.3,)"
      - dependency-name: "io.quarkus.platform:quarkus-camel-bom"
        versions: "[3.3,)"
      - dependency-name: "org.apache.activemq:*"
        versions: "[2.33.0,)"
    target-branch: "3.0.x"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.apache.maven.plugins:maven-compiler-plugin"
      - dependency-name: "io.quarkus:quarkus-bom"
        versions: "[3.0,)"
      - dependency-name: "io.quarkus.platform:quarkus-camel-bom"
        versions: "[3.0,)"
      - dependency-name: "io.quarkiverse:quarkiverse-parent"
        versions: "[16,)"
    target-branch: "2.x"
